### PR TITLE
test node 4 on travis

### PR DESCRIPTION
**Pull request by mapsam**
Updating travis to test on node 4.

### CODE REVIEW

**Comment by mapsam** [comment]
Looks like some weird errors here. The `s3prefixed.ls` portion just bails out after a few seconds, never sending anything to `data`, `end`, or `error` from the Readable stream. I'm not terribly familiar with streams - any ideas on this one @rclark?

**Comment by mapsam** [comment]
I do notice that `util.inherits` isn't fully supported any longer - possibly related. https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor

**Comment by rclark** [comment]
See https://github.com/mapbox/s3prefixed/pull/4 -- this ought to do the trick.

**Comment by mapsam** [comment]
That did it @rclark - thank you!

**Pull request merged**
